"""all

Revision ID: a098525e051d
Revises: 
Create Date: 2023-08-06 13:03:00.606980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a098525e051d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadeiras',
    sa.Column('unidade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('unidade_id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidade',
    sa.Column('id_cadeiras', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('n_unidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_cadeiras'),
    sa.UniqueConstraint('cidade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidade')
    op.drop_table('cadeiras')
    # ### end Alembic commands ###
